<div class="brands">
    <div class="product-brands">PRODUCT BRANDS</div>
    <div class="brand owl-carousel">
        <?php foreach ($block->getBrands() as $brand): ?>
            <div class="item"><a href="#"> <img src='<?= $brand->getImage(); ?>'></a></div>
        <?php endforeach; ?>
    </div>
</div>

<script type="text/javascript">
    require([
            'jquery',
            'owlcarousel'
        ], function ($, owlcarousel) {
            $(".brand").owlCarousel({
                loop: true,
                margin: 10,
                responsive: {
                    0: {
                        items: 1
                    },
                    600: {
                        items: 3
                    },
                    1000: {
                        items: 6
                    }
                }
            });
        }
    )
</script>


