<div class="testimonials">
    <div class="testimonials-title">TESTIMONIALS</div>
    <div class="testimonial owl-carousel">
        <?php foreach ($block->getTestimonials() as $testimonial): ?>
            <div class="testimonial-info">
                <div class="image">
                    <img src='<?php echo $block->getBaseMediaUrl() . 'yereone/image/' . $testimonial->getImage(); ?>'>
                </div>
                <div class="rating">
                    <?php for ( $i = 0; $i < $testimonial->getRating(); $i++): ?>
                        <img src='<?php echo $block->getBaseMediaUrl() . "testimonial/Star.svg" ?>'>
                    <?php endfor; ?>
                </div>
                <div class="text"><?= $testimonial->getText(); ?></div>
                <div class="info">
                    <span class="first-name"><?= $testimonial->getFirstName(); ?></span>
                    <span class="second-name"><?= $testimonial->getLastName(); ?></span>
                    <span class="flag">
                        <img src='<?php echo $block->getBaseMediaUrl() . 'yereone/flag/' . $testimonial->getFlag() . '.svg'; ?>'>
                    </span>
                </div>
                <div class="speciality"><?= $testimonial->getSpeciality(); ?></div>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<script type="text/javascript">
    require([
            'jquery',
            'owlcarousel'
        ], function ($, owlcarousel) {
            $(".testimonial").owlCarousel({
                loop: true,
                margin: 10,
                responsive: {
                    0: {
                        items: 1
                    },
                    600: {
                        items: 3
                    },
                    1000: {
                        items: 3
                    }
                }
            });
        }
    )
</script>