<div class="slider owl-carousel">
    <?php foreach ($block->getSlides() as $slide): ?>
        <div class="item <?= $slide->getPosition() ?>">
            <img src='<?php echo $block->getBaseMediaUrl() . 'yereone/image/' . $slide->getImage(); ?>'>
            <div class="slider-text"><?= $slide->getText(); ?></div>
        </div>
    <?php endforeach; ?>
</div>

<script type="text/javascript">
    require([
            'jquery',
            'owlcarousel'
        ], function ($, owlcarousel) {
            $(".slider").owlCarousel({
                loop: true,
                margin: 10,
                nav: true,
                <?php if ($block->getAutoplayTime()) : ?>
                autoplay: true,
                autoplayTimeout: <?= $block->getAutoplayTime() ?>,
                autoplayHoverPause: true,
                <?php endif; ?>
                responsive: {
                    0: {
                        items: 1
                    },
                    600: {
                        items: 3
                    },
                    1000: {
                        items: 1
                    }
                }
            });
        }
    )
</script>

