<div class="slider owl-carousel">
    <?php foreach ($block->getSlides() as $slide): ?>
        <div class="item"> <img src='<?= $slide->getPath(); ?>'></div>
    <?php endforeach; ?>
</div>

<script type="text/javascript">
    require([
            'jquery',
            'owlcarousel'
        ], function ($, owlcarousel) {
            $(".slider").owlCarousel({
                loop: true,
                margin: 10,
                nav: true,
                responsive: {
                    0: {
                        items: 1
                    },
                    600: {
                        items: 3
                    },
                    1000: {
                        items: 1
                    }
                }
            });
        }
    )
</script>

